const VOCAB_LA = {
"I Fundamenta":[
{"id":"la_f_001","w":"sum, esse","ph":"/sum ˈɛs.sɛ/","pos":"verbum","tr":"to be, exist","ex":"Cogito, ergo sum.","exTr":"I think, therefore I am. (Descartes)"},
{"id":"la_f_002","w":"et","ph":"/ɛt/","pos":"coniunctio","tr":"and, also, even","ex":"Senatus Populusque Romanus.","exTr":"The Senate and the Roman People."},
{"id":"la_f_003","w":"in","ph":"/ɪn/","pos":"praepositio","tr":"in, on, into (+ abl/acc)","ex":"In principio erat Verbum.","exTr":"In the beginning was the Word. (Ioh. 1:1)"},
{"id":"la_f_004","w":"non","ph":"/noːn/","pos":"adverbium","tr":"not, no","ex":"Non scholae sed vitae discimus.","exTr":"We learn not for school but for life. (Seneca)"},
{"id":"la_f_005","w":"is, ea, id","ph":"/ɪs eːa ɪd/","pos":"pronomen","tr":"he, she, it; that","ex":"Id est verum.","exTr":"That is true."},
{"id":"la_f_006","w":"qui, quae, quod","ph":"/kʷiː kʷaj kʷɔd/","pos":"pronomen","tr":"who, which, that","ex":"Homo qui non legit libros sapientiam non habet.","exTr":"A man who does not read books does not have wisdom."},
{"id":"la_f_007","w":"hic, haec, hoc","ph":"/hɪk haj hɔk/","pos":"pronomen","tr":"this, this one (nearby)","ex":"Hoc est corpus meum.","exTr":"This is my body. (Luc. 22:19)"},
{"id":"la_f_008","w":"dico, dicere","ph":"/ˈdiː.koː ˈdiː.kɛ.rɛ/","pos":"verbum","tr":"to say, tell, speak","ex":"Veni, vidi, vici — dixit Caesar.","exTr":"I came, I saw, I conquered — said Caesar."},
{"id":"la_f_009","w":"facio, facere","ph":"/ˈfa.ki.oː ˈfa.kɛ.rɛ/","pos":"verbum","tr":"to make, do, create","ex":"Fac quod debes.","exTr":"Do what you must."},
{"id":"la_f_010","w":"possum, posse","ph":"/ˈpɔs.sum ˈpɔs.sɛ/","pos":"verbum","tr":"to be able, can","ex":"Non omnia possumus omnes.","exTr":"We cannot all do everything. (Virgil)"},
{"id":"la_f_011","w":"homo, hominis","ph":"/ˈhɔ.moː ˈhɔ.mɪ.nɪs/","pos":"nomen (m)","tr":"person, human being","ex":"Homo homini lupus.","exTr":"Man is a wolf to man. (Plautus)"},
{"id":"la_f_012","w":"res, rei","ph":"/reːs reː.iː/","pos":"nomen (f)","tr":"thing, matter, affair, reality","ex":"Res publica est res populi.","exTr":"The republic is the affair of the people. (Cicero)"},
{"id":"la_f_013","w":"do, dare","ph":"/doː ˈda.rɛ/","pos":"verbum","tr":"to give","ex":"Da mihi ubi consistam et terram movebo.","exTr":"Give me a place to stand and I will move the earth. (Archimedes)"},
{"id":"la_f_014","w":"video, videre","ph":"/ˈwɪ.dɛ.oː wɪˈdɛ.rɛ/","pos":"verbum","tr":"to see, look at, consider","ex":"Veni, vidi, vici.","exTr":"I came, I saw, I conquered. (Caesar)"},
{"id":"la_f_015","w":"magnus, -a, -um","ph":"/ˈmaɡ.nʊs/","pos":"adiectivum","tr":"great, large, important","ex":"Magna cum laude.","exTr":"With great praise."},
{"id":"la_f_016","w":"bonus, -a, -um","ph":"/ˈbɔ.nʊs/","pos":"adiectivum","tr":"good, fine, brave","ex":"Omnia bona bonis.","exTr":"All things are good for the good."},
{"id":"la_f_017","w":"omnis, -e","ph":"/ˈɔm.nɪs/","pos":"adiectivum","tr":"all, every, whole","ex":"Omnia vincit Amor.","exTr":"Love conquers all. (Virgil)"},
{"id":"la_f_018","w":"ad","ph":"/ad/","pos":"praepositio","tr":"to, toward, near, for (+ acc)","ex":"Ad astra per aspera.","exTr":"To the stars through hardship."},
{"id":"la_f_019","w":"sed","ph":"/sɛd/","pos":"coniunctio","tr":"but, however, yet","ex":"Non progredi est regredi.","exTr":"Not to progress is to regress."},
{"id":"la_f_020","w":"ego","ph":"/ˈɛɡ.oː/","pos":"pronomen","tr":"I (emphatic)","ex":"Ego vero sic intellego.","exTr":"I indeed understand it thus. (Cicero)"},
{"id":"la_f_021","w":"ut","ph":"/ʊt/","pos":"coniunctio","tr":"as, so that, when, in order to","ex":"Ut ameris, ama.","exTr":"So that you may be loved, love. (Ovid)"},
{"id":"la_f_022","w":"cum","ph":"/kʊm/","pos":"praepositio/coniunctio","tr":"with (+ abl); when, since","ex":"Cum tacent, clamant.","exTr":"When they are silent, they cry out. (Cicero)"},
{"id":"la_f_023","w":"si","ph":"/siː/","pos":"coniunctio","tr":"if","ex":"Si vis pacem, para bellum.","exTr":"If you want peace, prepare for war."},
{"id":"la_f_024","w":"tempus, temporis","ph":"/ˈtɛm.pʊs ˈtɛm.pɔ.rɪs/","pos":"nomen (n)","tr":"time, occasion, season","ex":"Tempus fugit.","exTr":"Time flies. (Virgil)"},
{"id":"la_f_025","w":"via, viae","ph":"/ˈwɪ.a ˈwɪ.aj/","pos":"nomen (f)","tr":"road, way, street, method","ex":"Omnes viae Romam ducunt.","exTr":"All roads lead to Rome."},
{"id":"la_f_026","w":"nihil","ph":"/ˈnɪ.hɪl/","pos":"pronomen indecl.","tr":"nothing, not at all","ex":"Ex nihilo nihil fit.","exTr":"Nothing comes from nothing. (Lucretius)"},
{"id":"la_f_027","w":"pars, partis","ph":"/pars ˈpar.tɪs/","pos":"nomen (f)","tr":"part, portion, direction","ex":"Pars pro toto.","exTr":"The part for the whole."},
{"id":"la_f_028","w":"iam","ph":"/jaːm/","pos":"adverbium","tr":"now, already, soon","ex":"Iam tempus fugit.","exTr":"Already time flies."},
{"id":"la_f_029","w":"ille, illa, illud","ph":"/ˈɪl.lɛ ˈɪl.la ˈɪl.lʊd/","pos":"pronomen","tr":"that (over there), the famous","ex":"Ille homo stultus est.","exTr":"That man is foolish."},
{"id":"la_f_030","w":"unus, -a, -um","ph":"/ˈuː.nʊs/","pos":"numerale","tr":"one; a single, alone","ex":"E pluribus unum.","exTr":"Out of many, one. (US motto)"}
],
"II Grammatica":[
{"id":"la_g_001","w":"nomen, nominis","ph":"/ˈnoː.mɛn ˈnoː.mɪ.nɪs/","pos":"nomen (n)","tr":"name, noun; reputation","ex":"Nomen est omen.","exTr":"The name is a sign. (Plautus)"},
{"id":"la_g_002","w":"verbum, verbi","ph":"/ˈwɛr.bʊm ˈwɛr.biː/","pos":"nomen (n)","tr":"word, verb; speech","ex":"In principio erat Verbum.","exTr":"In the beginning was the Word. (John 1:1)"},
{"id":"la_g_003","w":"loquor, loqui","ph":"/ˈlɔ.kʷɔr ˈlɔ.kʷiː/","pos":"verbum","tr":"to speak, talk, say","ex":"Loquere ut te videam.","exTr":"Speak so that I may see you. (Socrates)"},
{"id":"la_g_004","w":"audio, audire","ph":"/ˈaw.dɪ.oː awˈdiː.rɛ/","pos":"verbum","tr":"to hear, listen, heed","ex":"Audi, vide, tace.","exTr":"Hear, see, be silent."},
{"id":"la_g_005","w":"scribo, scribere","ph":"/ˈskrɪ.boː ˈskrɪ.bɛ.rɛ/","pos":"verbum","tr":"to write, draw","ex":"Scripta manent, verba volant.","exTr":"Written words remain, spoken words fly away."},
{"id":"la_g_006","w":"lego, legere","ph":"/ˈlɛɡ.oː ˈlɛɡ.ɛ.rɛ/","pos":"verbum","tr":"to read; to choose, gather","ex":"Non multa sed multum.","exTr":"Not many things but much. (Pliny)"},
{"id":"la_g_007","w":"doceo, docere","ph":"/ˈdɔ.kɛ.oː dɔˈkɛː.rɛ/","pos":"verbum","tr":"to teach, instruct, explain","ex":"Docendo discimus.","exTr":"We learn by teaching."},
{"id":"la_g_008","w":"disco, discere","ph":"/ˈdɪs.koː ˈdɪs.kɛ.rɛ/","pos":"verbum","tr":"to learn, come to know","ex":"Non scholae sed vitae discimus.","exTr":"We learn not for school but for life."},
{"id":"la_g_009","w":"cogito, cogitare","ph":"/ˈkoɡ.ɪ.toː ˈkoɡ.ɪ.taː.rɛ/","pos":"verbum","tr":"to think, consider, reflect","ex":"Cogito, ergo sum.","exTr":"I think, therefore I am. (Descartes)"},
{"id":"la_g_010","w":"scio, scire","ph":"/ˈskɪ.oː ˈskiː.rɛ/","pos":"verbum","tr":"to know, understand","ex":"Scio me nihil scire.","exTr":"I know that I know nothing. (Socrates)"},
{"id":"la_g_011","w":"mens, mentis","ph":"/mɛːns ˈmɛn.tɪs/","pos":"nomen (f)","tr":"mind, reason, intention","ex":"Mens sana in corpore sano.","exTr":"A healthy mind in a healthy body. (Juvenal)"},
{"id":"la_g_012","w":"ratio, rationis","ph":"/ˈra.tɪ.oː raˈtɪ.oː.nɪs/","pos":"nomen (f)","tr":"reason, method, account","ex":"Ratio recta est.","exTr":"Right reason prevails."},
{"id":"la_g_013","w":"causa, causae","ph":"/ˈkaw.sa ˈkaw.saj/","pos":"nomen (f)","tr":"cause, reason, purpose, case","ex":"Causa sine qua non.","exTr":"A cause without which not (indispensable condition)."},
{"id":"la_g_014","w":"vox, vocis","ph":"/woːks ˈwoː.kɪs/","pos":"nomen (f)","tr":"voice, word, sound, speech","ex":"Vox populi, vox Dei.","exTr":"The voice of the people is the voice of God."},
{"id":"la_g_015","w":"sententia, sententiae","ph":"/sɛnˈtɛn.tɪ.a/","pos":"nomen (f)","tr":"opinion, sentence, meaning","ex":"Tot homines, quot sententiae.","exTr":"As many opinions as there are people. (Terence)"},
{"id":"la_g_016","w":"ars, artis","ph":"/ars ˈar.tɪs/","pos":"nomen (f)","tr":"art, skill, craft, method","ex":"Ars longa, vita brevis.","exTr":"Art is long, life is short. (Hippocrates)"},
{"id":"la_g_017","w":"sapientia, sapientiae","ph":"/saˈpɪ.ɛn.tɪ.a/","pos":"nomen (f)","tr":"wisdom, good sense","ex":"Initium sapientiae est timor Domini.","exTr":"The beginning of wisdom is fear of the Lord."},
{"id":"la_g_018","w":"memoria, memoriae","ph":"/mɛˈmoː.rɪ.a/","pos":"nomen (f)","tr":"memory, remembrance, record","ex":"In memoriam.","exTr":"In memory of."},
{"id":"la_g_019","w":"liber, libri","ph":"/ˈlɪ.bɛr ˈlɪ.briː/","pos":"nomen (m)","tr":"book","ex":"Libri sunt amici silentes.","exTr":"Books are silent friends."},
{"id":"la_g_020","w":"littera, litterae","ph":"/ˈlɪt.tɛ.ra ˈlɪt.tɛ.raj/","pos":"nomen (f)","tr":"letter (alphabet); pl. literature","ex":"Litterae non erubescunt.","exTr":"Letters do not blush. (Cicero)"},
{"id":"la_g_021","w":"verus, -a, -um","ph":"/ˈwɛː.rʊs/","pos":"adiectivum","tr":"true, real, actual, genuine","ex":"In vino veritas.","exTr":"In wine is truth. (Pliny the Elder)"},
{"id":"la_g_022","w":"multus, -a, -um","ph":"/ˈmʊl.tʊs/","pos":"adiectivum","tr":"much, many, numerous","ex":"Multi sunt vocati, pauci vero electi.","exTr":"Many are called, but few are chosen. (Matt. 22:14)"},
{"id":"la_g_023","w":"novus, -a, -um","ph":"/ˈnɔ.wʊs/","pos":"adiectivum","tr":"new, fresh, strange, novel","ex":"Nihil novi sub sole.","exTr":"Nothing new under the sun. (Eccl. 1:9)"},
{"id":"la_g_024","w":"certus, -a, -um","ph":"/ˈkɛr.tʊs/","pos":"adiectivum","tr":"certain, sure, fixed","ex":"Certis ingeniis immorari.","exTr":"To dwell on certain subjects."},
{"id":"la_g_025","w":"communis, -e","ph":"/kɔmˈmuː.nɪs/","pos":"adiectivum","tr":"common, shared, public","ex":"Loca communia.","exTr":"Common places (commonplaces)."},
{"id":"la_g_026","w":"sensus, sensus","ph":"/ˈsɛn.sʊs/","pos":"nomen (m)","tr":"sense, feeling, meaning","ex":"Sensum communem habes.","exTr":"You have common sense."},
{"id":"la_g_027","w":"oratio, orationis","ph":"/oˈra.tɪ.oː/","pos":"nomen (f)","tr":"speech, oration, prayer","ex":"Oratio est imago animi.","exTr":"Speech is the image of the soul. (Publilius Syrus)"},
{"id":"la_g_028","w":"intellectus, intellectus","ph":"/ɪnˈtɛl.lɛk.tʊs/","pos":"nomen (m)","tr":"understanding, intelligence","ex":"Intellectus est ultima perfectio animae.","exTr":"Intellect is the ultimate perfection of the soul. (Aquinas)"},
{"id":"la_g_029","w":"quaero, quaerere","ph":"/ˈkʷaj.roː kʷajˈrɛː.rɛ/","pos":"verbum","tr":"to seek, ask, inquire","ex":"Quaere verum.","exTr":"Seek the truth."},
{"id":"la_g_030","w":"proprius, -a, -um","ph":"/ˈprɔ.prɪ.ʊs/","pos":"adiectivum","tr":"one's own, particular, proper","ex":"Proprium humani ingenii est odisse quem laeseris.","exTr":"It is human to hate one whom you have injured. (Tacitus)"}
],
"III Classica":[
{"id":"la_c_001","w":"bellum, belli","ph":"/ˈbɛl.lʊm ˈbɛl.liː/","pos":"nomen (n)","tr":"war, combat, conflict","ex":"Si vis pacem, para bellum.","exTr":"If you want peace, prepare for war."},
{"id":"la_c_002","w":"pax, pacis","ph":"/paks ˈpa.kɪs/","pos":"nomen (f)","tr":"peace, tranquility, favour","ex":"Pax Romana.","exTr":"The Roman Peace."},
{"id":"la_c_003","w":"populus, populi","ph":"/ˈpɔ.pʊ.lʊs ˈpɔ.pʊ.liː/","pos":"nomen (m)","tr":"people, nation, crowd","ex":"Vox populi, vox Dei.","exTr":"The voice of the people is the voice of God."},
{"id":"la_c_004","w":"rex, regis","ph":"/rɛks ˈrɛɡ.ɪs/","pos":"nomen (m)","tr":"king, ruler","ex":"Dura lex, sed lex.","exTr":"The law is harsh, but it is the law."},
{"id":"la_c_005","w":"lex, legis","ph":"/lɛks ˈlɛɡ.ɪs/","pos":"nomen (f)","tr":"law, rule, condition","ex":"Dura lex, sed lex.","exTr":"The law is harsh, but it is the law."},
{"id":"la_c_006","w":"civitas, civitatis","ph":"/ˈkɪ.wɪ.tas kɪˈwɪ.ta.tɪs/","pos":"nomen (f)","tr":"state, city, community","ex":"Civis Romanus sum.","exTr":"I am a Roman citizen. (Cicero)"},
{"id":"la_c_007","w":"virtus, virtutis","ph":"/ˈwɪr.tʊs wɪrˈtuː.tɪs/","pos":"nomen (f)","tr":"virtue, courage, excellence","ex":"Virtus in actione consistit.","exTr":"Virtue consists in action."},
{"id":"la_c_008","w":"gloria, gloriae","ph":"/ˈɡlɔ.rɪ.a ˈɡlɔ.rɪ.aj/","pos":"nomen (f)","tr":"glory, fame, renown","ex":"Sic transit gloria mundi.","exTr":"Thus passes the glory of the world."},
{"id":"la_c_009","w":"amor, amoris","ph":"/ˈa.mɔr aˈmoː.rɪs/","pos":"nomen (m)","tr":"love, desire, affection","ex":"Omnia vincit Amor.","exTr":"Love conquers all. (Virgil)"},
{"id":"la_c_010","w":"fortuna, fortunae","ph":"/fɔrˈtuː.na fɔrˈtuː.naj/","pos":"nomen (f)","tr":"fortune, fate, luck","ex":"Fortes fortuna adiuvat.","exTr":"Fortune favours the brave. (Terence)"},
{"id":"la_c_011","w":"natura, naturae","ph":"/naˈtuː.ra naˈtuː.raj/","pos":"nomen (f)","tr":"nature, character, essence","ex":"Naturam expellas furca, tamen recurret.","exTr":"Drive out nature with a fork, yet she always returns. (Horace)"},
{"id":"la_c_012","w":"corpus, corporis","ph":"/ˈkɔr.pʊs ˈkɔr.pɔ.rɪs/","pos":"nomen (n)","tr":"body, physical form","ex":"Mens sana in corpore sano.","exTr":"A sound mind in a sound body. (Juvenal)"},
{"id":"la_c_013","w":"anima, animae","ph":"/ˈa.nɪ.ma ˈa.nɪ.maj/","pos":"nomen (f)","tr":"breath, soul, spirit, life","ex":"Dum spiro, spero.","exTr":"While I breathe, I hope. (Cicero)"},
{"id":"la_c_014","w":"vita, vitae","ph":"/ˈwɪ.ta ˈwɪ.taj/","pos":"nomen (f)","tr":"life, way of life","ex":"Ars longa, vita brevis.","exTr":"Art is long, life is short."},
{"id":"la_c_015","w":"mors, mortis","ph":"/mɔrs ˈmɔr.tɪs/","pos":"nomen (f)","tr":"death, destruction","ex":"Mors omnia aequat.","exTr":"Death makes all equal. (Claudian)"},
{"id":"la_c_016","w":"terra, terrae","ph":"/ˈtɛr.ra ˈtɛr.raj/","pos":"nomen (f)","tr":"earth, land, ground, soil","ex":"Terra incognita.","exTr":"Unknown land."},
{"id":"la_c_017","w":"caelum, caeli","ph":"/ˈkaj.lʊm ˈkaj.liː/","pos":"nomen (n)","tr":"sky, heaven, climate","ex":"Ad astra.","exTr":"To the stars."},
{"id":"la_c_018","w":"pater, patris","ph":"/ˈpa.tɛr ˈpa.trɪs/","pos":"nomen (m)","tr":"father, ancestor, senator","ex":"Pater familias.","exTr":"Father of the household."},
{"id":"la_c_019","w":"mater, matris","ph":"/ˈma.tɛr ˈma.trɪs/","pos":"nomen (f)","tr":"mother, origin, source","ex":"Alma mater.","exTr":"Nourishing mother (one's university)."},
{"id":"la_c_020","w":"vir, viri","ph":"/wɪr ˈwɪ.riː/","pos":"nomen (m)","tr":"man, hero, husband","ex":"Vir bonus est quis?","exTr":"Who is a good man? (Horace)"},
{"id":"la_c_021","w":"amicus, amici","ph":"/aˈmiː.kʊs aˈmiː.kiː/","pos":"nomen (m)","tr":"friend, ally","ex":"Amicus certus in re incerta cernitur.","exTr":"A true friend is seen in uncertain times. (Ennius)"},
{"id":"la_c_022","w":"deus, dei","ph":"/ˈdɛ.ʊs ˈdɛ.iː/","pos":"nomen (m)","tr":"god, deity","ex":"Deus ex machina.","exTr":"God from the machine (an unexpected saviour)."},
{"id":"la_c_023","w":"fides, fidei","ph":"/ˈfɪ.dɛs ˈfɪ.dɛ.iː/","pos":"nomen (f)","tr":"faith, trust, loyalty, pledge","ex":"Bona fides.","exTr":"Good faith."},
{"id":"la_c_024","w":"honor, honoris","ph":"/ˈhɔ.nɔr hɔˈnoː.rɪs/","pos":"nomen (m)","tr":"honor, dignity, office","ex":"Honoris causa.","exTr":"For the sake of honor (honorary degree)."},
{"id":"la_c_025","w":"imperium, imperii","ph":"/ɪmˈpɛ.rɪ.ʊm ɪmˈpɛ.rɪ.iː/","pos":"nomen (n)","tr":"power, command, empire","ex":"Imperium sine fine dedi.","exTr":"I have given empire without end. (Virgil)"},
{"id":"la_c_026","w":"sol, solis","ph":"/sɔl ˈsɔ.lɪs/","pos":"nomen (m)","tr":"sun; day; sunlight","ex":"Nihil novi sub sole.","exTr":"Nothing new under the sun."},
{"id":"la_c_027","w":"lux, lucis","ph":"/lʊks ˈluː.kɪs/","pos":"nomen (f)","tr":"light, daylight, life","ex":"Lux et veritas.","exTr":"Light and truth. (Yale motto)"},
{"id":"la_c_028","w":"aqua, aquae","ph":"/ˈa.kʷa ˈa.kʷaj/","pos":"nomen (f)","tr":"water","ex":"Aqua vitae.","exTr":"Water of life (distilled spirits)."},
{"id":"la_c_029","w":"caput, capitis","ph":"/ˈka.pʊt ˈka.pɪ.tɪs/","pos":"nomen (n)","tr":"head, top, capital, chief","ex":"Caput mundi.","exTr":"Head of the world (Rome)."},
{"id":"la_c_030","w":"manus, manus","ph":"/ˈma.nʊs/","pos":"nomen (f)","tr":"hand, band of men","ex":"Manus manum lavat.","exTr":"One hand washes the other. (Petronius)"}
],
"IV Philosophica":[
{"id":"la_p_001","w":"veritas, veritatis","ph":"/ˈwɛ.rɪ.tas wɛˈrɪ.ta.tɪs/","pos":"nomen (f)","tr":"truth, reality, sincerity","ex":"Veritas vos liberabit.","exTr":"The truth will set you free. (John 8:32)"},
{"id":"la_p_002","w":"iustitia, iustitiae","ph":"/juːˈstɪ.tɪ.a/","pos":"nomen (f)","tr":"justice, fairness, equity","ex":"Fiat iustitia, ruat caelum.","exTr":"Let justice be done, though the heavens fall."},
{"id":"la_p_003","w":"libertas, libertatis","ph":"/lɪˈbɛr.tas lɪˈbɛr.ta.tɪs/","pos":"nomen (f)","tr":"freedom, liberty, independence","ex":"Libertas inaestimabilis res est.","exTr":"Freedom is a priceless thing. (Ulpian)"},
{"id":"la_p_004","w":"voluntas, voluntatis","ph":"/wɔˈlʊn.tas wɔˈlʊn.ta.tɪs/","pos":"nomen (f)","tr":"will, wish, desire, consent","ex":"Voluntas est superior intellectu.","exTr":"Will is superior to intellect. (Duns Scotus)"},
{"id":"la_p_005","w":"forma, formae","ph":"/ˈfɔr.ma ˈfɔr.maj/","pos":"nomen (f)","tr":"form, shape, beauty, kind","ex":"Forma dat esse.","exTr":"Form gives being. (Scholastic principle)"},
{"id":"la_p_006","w":"essentia, essentiae","ph":"/ɛsˈsɛn.tɪ.a/","pos":"nomen (f)","tr":"essence, being, nature","ex":"Essentia sequitur esse.","exTr":"Essence follows existence."},
{"id":"la_p_007","w":"principium, principii","ph":"/prɪnˈkɪ.pɪ.ʊm/","pos":"nomen (n)","tr":"beginning, origin, principle","ex":"In principio erat Verbum.","exTr":"In the beginning was the Word."},
{"id":"la_p_008","w":"finis, finis","ph":"/ˈfɪ.nɪs/","pos":"nomen (m)","tr":"end, limit, aim, death","ex":"Finis coronat opus.","exTr":"The end crowns the work."},
{"id":"la_p_009","w":"felix, felicis","ph":"/ˈfɛ.lɪks fɛˈlɪ.kɪs/","pos":"adiectivum","tr":"happy, fortunate, fruitful","ex":"Felix qui potuit rerum cognoscere causas.","exTr":"Happy is he who has learned the causes of things. (Virgil)"},
{"id":"la_p_010","w":"aeternus, -a, -um","ph":"/ajˈtɛr.nʊs/","pos":"adiectivum","tr":"eternal, everlasting, perpetual","ex":"Sub specie aeternitatis.","exTr":"Under the aspect of eternity. (Spinoza)"},
{"id":"la_p_011","w":"verum, veri","ph":"/ˈwɛː.rʊm/","pos":"nomen (n)","tr":"truth, the true, reality","ex":"Verum ipsum factum.","exTr":"The true is the made itself. (Vico)"},
{"id":"la_p_012","w":"bonum, boni","ph":"/ˈbɔ.nʊm/","pos":"nomen (n)","tr":"good, benefit, virtue","ex":"Summum bonum.","exTr":"The highest good. (Cicero)"},
{"id":"la_p_013","w":"dubium, dubii","ph":"/ˈdʊ.bɪ.ʊm/","pos":"nomen (n)","tr":"doubt, uncertainty","ex":"Sine dubio.","exTr":"Without doubt."},
{"id":"la_p_014","w":"casus, casus","ph":"/ˈka.sʊs/","pos":"nomen (m)","tr":"fall, accident, chance, fate","ex":"Casus belli.","exTr":"An occasion for war."},
{"id":"la_p_015","w":"consensus, consensus","ph":"/kɔnˈsɛn.sʊs/","pos":"nomen (m)","tr":"agreement, harmony, consent","ex":"Consensus gentium.","exTr":"The agreement of nations."},
{"id":"la_p_016","w":"puto, putare","ph":"/ˈpʊ.toː ˈpʊ.ta.rɛ/","pos":"verbum","tr":"to think, consider, believe","ex":"Quid putas?","exTr":"What do you think?"},
{"id":"la_p_017","w":"spero, sperare","ph":"/ˈspɛ.roː ˈspɛ.ra.rɛ/","pos":"verbum","tr":"to hope, expect, trust","ex":"Dum spiro, spero.","exTr":"While I breathe, I hope. (Cicero)"},
{"id":"la_p_018","w":"timeo, timere","ph":"/ˈtɪ.mɛ.oː tɪˈmɛː.rɛ/","pos":"verbum","tr":"to fear, be afraid of, dread","ex":"Timeo Danaos et dona ferentes.","exTr":"I fear the Greeks even when bearing gifts. (Virgil)"},
{"id":"la_p_019","w":"volo, velle","ph":"/ˈwɔ.loː ˈwɛl.lɛ/","pos":"verbum","tr":"to wish, want, be willing","ex":"Ubi vis, ibi via.","exTr":"Where there is a will, there is a way."},
{"id":"la_p_020","w":"intellego, intellegere","ph":"/ɪnˈtɛl.lɛ.ɡoː ɪnˈtɛl.lɛ.ɡɛ.rɛ/","pos":"verbum","tr":"to understand, perceive, realize","ex":"Intellege ut credas.","exTr":"Understand so that you may believe. (Augustine)"},
{"id":"la_p_021","w":"materia, materiae","ph":"/maˈtɛ.rɪ.a/","pos":"nomen (f)","tr":"matter, material, subject","ex":"Ex materia et forma compositum.","exTr":"Composed of matter and form. (Aristotle)"},
{"id":"la_p_022","w":"necessarius, -a, -um","ph":"/nɛkɛsˈsa.rɪ.ʊs/","pos":"adiectivum","tr":"necessary, inevitable, essential","ex":"Conditio sine qua non.","exTr":"An indispensable condition."},
{"id":"la_p_023","w":"liber, libera, liberum","ph":"/ˈlɪ.bɛr ˈlɪ.bɛ.ra ˈlɪ.bɛ.rʊm/","pos":"adiectivum","tr":"free, independent, unrestrained","ex":"Libero more vivere.","exTr":"To live in the manner of a free man."},
{"id":"la_p_024","w":"nolo, nolle","ph":"/ˈnoː.loː ˈnɔl.lɛ/","pos":"verbum","tr":"to be unwilling, not to want","ex":"Nolo contendere.","exTr":"I do not wish to contend (legal term)."},
{"id":"la_p_025","w":"malo, malle","ph":"/ˈmaː.loː ˈmal.lɛ/","pos":"verbum","tr":"to prefer, rather want","ex":"Malo mori quam foedari.","exTr":"I prefer to die rather than be dishonoured."},
{"id":"la_p_026","w":"prima facie","ph":"/ˈpriː.ma ˈfa.kɪ.ɛ/","pos":"locutio","tr":"at first sight, on the face of it","ex":"Prima facie vera esse videtur haec sententia.","exTr":"This statement seems true at first sight."},
{"id":"la_p_027","w":"per se","ph":"/pɛr seː/","pos":"locutio","tr":"by itself, in itself, intrinsically","ex":"Nihil per se bonum aut malum est.","exTr":"Nothing is good or bad in itself. (Seneca)"},
{"id":"la_p_028","w":"a priori","ph":"/aː priˈɔː.riː/","pos":"locutio","tr":"from before; reasoning before experience","ex":"Cognitio a priori.","exTr":"Knowledge a priori (independent of experience). (Kant)"},
{"id":"la_p_029","w":"a posteriori","ph":"/aː pɔs.tɛˈriˈɔː.riː/","pos":"locutio","tr":"from after; reasoning from experience","ex":"Cognitio a posteriori.","exTr":"Knowledge a posteriori (derived from experience). (Kant)"},
{"id":"la_p_030","w":"felix culpa","ph":"/ˈfɛ.lɪks ˈkʊl.pa/","pos":"locutio","tr":"happy fault, blessed mistake","ex":"O felix culpa, quae talem meruit habere redemptorem.","exTr":"O happy fault that merited such a Redeemer. (Augustine)"}
],
"V Poetica":[
{"id":"la_q_001","w":"carmen, carminis","ph":"/ˈkar.mɛn ˈkar.mɪ.nɪs/","pos":"nomen (n)","tr":"song, poem, incantation, verse","ex":"Carmen perpetuum.","exTr":"A continuous song. (Ovid, opening of Metamorphoses)"},
{"id":"la_q_002","w":"carpe diem","ph":"/ˈkar.pɛ ˈdɪ.ɛm/","pos":"locutio","tr":"seize the day","ex":"Carpe diem, quam minimum credula postero.","exTr":"Seize the day, trusting as little as possible to the future. (Horace)"},
{"id":"la_q_003","w":"pulcher, pulchra, pulchrum","ph":"/ˈpʊl.kɛr ˈpʊl.kra ˈpʊl.krʊm/","pos":"adiectivum","tr":"beautiful, handsome, noble","ex":"Dulce et decorum est pro patria mori.","exTr":"It is sweet and fitting to die for one's country. (Horace)"},
{"id":"la_q_004","w":"dulcis, -e","ph":"/ˈdʊl.kɪs/","pos":"adiectivum","tr":"sweet, pleasant, dear, gentle","ex":"Dulce et decorum est pro patria mori.","exTr":"It is sweet and fitting to die for one's country. (Horace)"},
{"id":"la_q_005","w":"nox, noctis","ph":"/nɔks ˈnɔk.tɪs/","pos":"nomen (f)","tr":"night, darkness, death","ex":"Per noctem iter fecimus.","exTr":"We made the journey through the night."},
{"id":"la_q_006","w":"flos, floris","ph":"/floːs ˈfloː.rɪs/","pos":"nomen (m)","tr":"flower, blossom, prime of youth","ex":"Flores calcamus.","exTr":"We tread on flowers."},
{"id":"la_q_007","w":"fugit, fugere","ph":"/ˈfʊ.ɡɪt ˈfʊ.ɡɛ.rɛ/","pos":"verbum","tr":"to flee, escape, pass (of time)","ex":"Sed fugit interea, fugit inreparabile tempus.","exTr":"But meanwhile it flees, irretrievably time flees. (Virgil)"},
{"id":"la_q_008","w":"cano, canere","ph":"/ˈka.noː ˈka.nɛ.rɛ/","pos":"verbum","tr":"to sing, play music, chant","ex":"Arma virumque cano.","exTr":"I sing of arms and the man. (Virgil, opening of Aeneid)"},
{"id":"la_q_009","w":"amo, amare","ph":"/ˈa.moː ˈa.ma.rɛ/","pos":"verbum","tr":"to love, like, be fond of","ex":"Ama et fac quod vis.","exTr":"Love and do what you will. (Augustine)"},
{"id":"la_q_010","w":"dolor, doloris","ph":"/ˈdɔ.lɔr dɔˈloː.rɪs/","pos":"nomen (m)","tr":"pain, grief, anguish, sorrow","ex":"Forsan et haec olim meminisse iuvabit.","exTr":"Perhaps it will be a pleasure to remember even these things. (Virgil)"},
{"id":"la_q_011","w":"lacrimae, lacrimarum","ph":"/ˈla.krɪ.maj/","pos":"nomen (f pl)","tr":"tears","ex":"Sunt lacrimae rerum.","exTr":"There are tears for things. (Virgil, Aeneid I)"},
{"id":"la_q_012","w":"spes, spei","ph":"/spɛːs ˈspɛ.iː/","pos":"nomen (f)","tr":"hope, expectation","ex":"Dum spiro, spero.","exTr":"While I breathe, I hope."},
{"id":"la_q_013","w":"aurum, auri","ph":"/ˈaw.rʊm ˈaw.riː/","pos":"nomen (n)","tr":"gold, money, riches","ex":"Aurea mediocritas.","exTr":"The golden mean. (Horace)"},
{"id":"la_q_014","w":"silva, silvae","ph":"/ˈsɪl.wa ˈsɪl.waj/","pos":"nomen (f)","tr":"forest, wood, mass","ex":"Quo vadis in silvam?","exTr":"Where are you going into the forest?"},
{"id":"la_q_015","w":"mare, maris","ph":"/ˈma.rɛ ˈma.rɪs/","pos":"nomen (n)","tr":"sea, ocean","ex":"Mare nostrum.","exTr":"Our sea (Roman name for the Mediterranean)."},
{"id":"la_q_016","w":"ignis, ignis","ph":"/ˈɪɡ.nɪs/","pos":"nomen (m)","tr":"fire, flame, passion","ex":"Ignis aurum probat.","exTr":"Fire tests gold. (Seneca)"},
{"id":"la_q_017","w":"luna, lunae","ph":"/ˈluː.na ˈluː.naj/","pos":"nomen (f)","tr":"moon, month, crescent","ex":"Luna silentio labitur.","exTr":"The moon glides in silence."},
{"id":"la_q_018","w":"cor, cordis","ph":"/kɔr ˈkɔr.dɪs/","pos":"nomen (n)","tr":"heart, mind, feeling","ex":"Cor ad cor loquitur.","exTr":"Heart speaks to heart. (Newman's motto)"},
{"id":"la_q_019","w":"umbra, umbrae","ph":"/ˈʊm.bra ˈʊm.braj/","pos":"nomen (f)","tr":"shadow, shade, ghost","ex":"Stat magni nominis umbra.","exTr":"He stands the shadow of a great name. (Lucan)"},
{"id":"la_q_020","w":"musa, musae","ph":"/ˈmuː.sa ˈmuː.saj/","pos":"nomen (f)","tr":"Muse (goddess of arts); talent","ex":"Musa mihi causas memora.","exTr":"O Muse, recall the causes for me. (Virgil, Aeneid I)"},
{"id":"la_q_021","w":"aurora, aurorae","ph":"/awˈroː.ra awˈroː.raj/","pos":"nomen (f)","tr":"dawn, goddess of dawn, east","ex":"Aurora musis amica.","exTr":"Dawn is the friend of the Muses."},
{"id":"la_q_022","w":"memento mori","ph":"/mɛˈmɛn.toː ˈmoː.riː/","pos":"locutio","tr":"remember you must die","ex":"Memento mori — et carpe diem.","exTr":"Remember you will die — and seize the day."},
{"id":"la_q_023","w":"vox clamantis","ph":"/wɔks klaˈman.tɪs/","pos":"locutio","tr":"voice of one crying out","ex":"Vox clamantis in deserto.","exTr":"A voice crying out in the wilderness. (Isaiah 40:3)"},
{"id":"la_q_024","w":"odi et amo","ph":"/ˈɔ.diː ɛt ˈa.moː/","pos":"locutio","tr":"I hate and I love","ex":"Odi et amo. Quare id faciam, fortasse requiris.","exTr":"I hate and I love. Why I do this, perhaps you ask. (Catullus 85)"},
{"id":"la_q_025","w":"puer, pueri","ph":"/ˈpʊ.ɛr ˈpʊ.ɛ.riː/","pos":"nomen (m)","tr":"boy, child, young man","ex":"Puer aeternus.","exTr":"The eternal boy (Jungian archetype)."},
{"id":"la_q_026","w":"venti, ventorum","ph":"/ˈwɛn.tiː/","pos":"nomen (m pl)","tr":"winds","ex":"Ventis secundis.","exTr":"With favourable winds."},
{"id":"la_q_027","w":"silva rerum","ph":"/ˈsɪl.wa ˈrɛ.rʊm/","pos":"locutio","tr":"forest of things (a collection)","ex":"Silva rerum in hac bibliotheca.","exTr":"A forest of things in this library."},
{"id":"la_q_028","w":"in medias res","ph":"/ɪn ˈmɛ.dɪ.as rɛs/","pos":"locutio","tr":"into the middle of things","ex":"In medias res poeta nos ducit.","exTr":"The poet leads us into the middle of things. (Horace)"},
{"id":"la_q_029","w":"ex tempore","ph":"/ɛks ˈtɛm.pɔ.rɛ/","pos":"locutio","tr":"out of the moment; impromptu","ex":"Orator ex tempore loquitur.","exTr":"The orator speaks impromptu."},
{"id":"la_q_030","w":"amor fati","ph":"/ˈa.mɔr ˈfa.tiː/","pos":"locutio","tr":"love of fate","ex":"Amor fati — hoc est formula mea.","exTr":"Love of fate — this is my formula. (Nietzsche)"}
]
};
